language: node_js
node_js:
  - 12
  - 14
cache:
  directories:
    - node_modules

install:
  - npm install -g cmake-js
  - yarn install --frozen-lockfile

script:
  - yarn run compile
  - yarn run test
